import { chromium } from 'playwright';
import fs from 'node:fs';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
fs.mkdirSync('temp/checks',{recursive:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('response',response=>{if(response.status()>=400)errors.push(`${response.status()} ${response.url()}`);});
await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});
await page.screenshot({path:'temp/checks/desktop.png',fullPage:true});
const assert=(value,message)=>{if(!value)throw new Error(message);};
assert(await page.locator('#current-flow>li').count()===10,'Current flow must have 10 steps');
assert(await page.locator('#improved-flow>li').count()===10,'Improved flow must have 10 steps');
await page.getByRole('button',{name:'Improved process',exact:true}).click();
assert(!await page.locator('.current-panel').isVisible(),'Current panel must hide');
assert(await page.locator('.improved-panel').isVisible(),'Improved panel must show');
await page.getByRole('button',{name:'Current process',exact:true}).click();
assert(!await page.locator('.improved-panel').isVisible(),'Improved panel must hide');
await page.getByRole('button',{name:'Side by side'}).click();
await page.getByRole('button',{name:'Sequence words: on'}).click();
assert(await page.locator('.prose-flow').evaluate(el=>el.classList.contains('no-highlight')),'Highlight control failed');
await page.getByRole('button',{name:'Sequence words: off'}).click();
await page.locator('.problem').nth(1).locator('summary').click();
assert(await page.locator('.problem').nth(1).getAttribute('open')!==null,'Problem disclosure failed');
await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile horizontal overflow');
await page.getByRole('button',{name:'Menu'}).click();
assert(await page.locator('#navigation').isVisible(),'Mobile menu did not open');
await page.getByRole('navigation',{name:'Main navigation'}).getByRole('link',{name:'Explanation'}).click();
assert(!await page.locator('#navigation').isVisible(),'Mobile menu did not close');
await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});
await page.screenshot({path:'temp/checks/mobile.png',fullPage:true});
await page.setViewportSize({width:320,height:740});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320px horizontal overflow');
await page.emulateMedia({reducedMotion:'reduce'});
assert(await page.evaluate(()=>getComputedStyle(document.documentElement).scrollBehavior)==='auto','Reduced motion not respected');
await page.emulateMedia({media:'print'});
assert(await page.locator('.current-panel').isVisible()&&await page.locator('.improved-panel').isVisible(),'Print must include both flows');
console.log(JSON.stringify({passed:true,checks:['20 flow steps','three view modes','sequence toggle','problem disclosure','mobile menu','320px and 390px overflow','reduced motion','print layout'],errors},null,2));
await browser.close();
if(errors.length)process.exitCode=1;
